-- SQL Script to set up your Supabase Database for HireAI

-- Enable RLS (Recommended)
ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;

-- Create Users table (if not using Supabase Auth Default, but it's better to use Auth)
-- For this app, we'll store extra profile data in a 'profiles' table that links to auth.users

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  image TEXT,
  last_ats_score INTEGER,
  industry_fit TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create Jobs table for saved jobs
CREATE TABLE IF NOT EXISTS public.saved_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  salary TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS Policies
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view their own saved jobs" ON public.saved_jobs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add their own saved jobs" ON public.saved_jobs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own saved jobs" ON public.saved_jobs FOR DELETE USING (auth.uid() = user_id);
